name: Build

on:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Create and enter build directory
        run: |
          mkdir build
          cd build

      - name: Configure CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DLLVM_TARGETS_TO_BUILD="X86" -G "NMake Makefiles" ..

      - name: Build with NMake
        run: |
          nmake
